# Generated by Django 5.0.1 on 2025-12-11 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yutuq nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon (emoji)')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Ball')),
                ('condition_type', models.CharField(choices=[('books_read', "O'qilgan kitoblar soni"), ('streak_days', 'Streak kunlar'), ('total_pages', 'Jami sahifalar'), ('quiz_score', 'Test ballari')], max_length=50, verbose_name='Shart turi')),
                ('condition_value', models.PositiveIntegerField(verbose_name='Shart qiymati')),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
            },
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('pages_read', models.PositiveIntegerField(default=0, verbose_name="O'qilgan sahifalar")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streaks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kunlik streak',
                'verbose_name_plural': 'Kunlik streaklar',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_read', models.PositiveIntegerField(default=0, verbose_name="O'qilgan sahifalar")),
                ('current_page', models.PositiveIntegerField(default=0, verbose_name='Joriy sahifa')),
                ('completed', models.BooleanField(default=False, verbose_name='Tugatildi')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='books.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'qish sessiyasi",
                'verbose_name_plural': "O'qish sessiyalari",
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.achievement', verbose_name='Yutuq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi yutuqi',
                'verbose_name_plural': 'Foydalanuvchi yutuqlari',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
