# Generated by Django 5.0.1 on 2025-12-12 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comparison_html', models.TextField(help_text='AI tomonidan yaratilgan taqqoslash matni (HTML format)', verbose_name='Taqqoslash HTML')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('book1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_book1', to='books.book', verbose_name='Birinchi kitob')),
                ('book2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_book2', to='books.book', verbose_name='Ikkinchi kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comparisons', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kitoblar taqqoslashi',
                'verbose_name_plural': 'Kitoblar taqqoslashlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_chat_boo_user_id_5c8f4e_idx'), models.Index(fields=['book1', 'book2'], name='ai_chat_boo_book1_i_c667fa_idx')],
            },
        ),
    ]
