# Generated by Django 5.0.1 on 2025-12-11 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Rasm')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name="Tug'ilgan yili")),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki icon class', max_length=50)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Kitob nomi')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Muqova')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='PDF fayl')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Sahifalar soni')),
                ('language', models.CharField(choices=[('uzbek', "O'zbek"), ('russian', 'Rus'), ('english', 'Ingliz')], default='uzbek', max_length=20, verbose_name='Til')),
                ('published_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nashr yili')),
                ('content_text', models.TextField(blank=True, verbose_name='Kitob matni (AI uchun)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author', verbose_name='Muallif')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-created_at'],
            },
        ),
    ]
